import { resolve } from 'node:path';
import { z } from 'zod';
import { PASSWORD_HASH_PREFIX } from '../auth/password.js';

const booleanString = z.enum(['true', 'false']).transform((value) => value === 'true');

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  HOST: z.string().default('0.0.0.0'),
  PORT: z.coerce.number().int().min(1).max(65535).default(3000),
  DATABASE_PATH: z.string().min(1).default('data/team-radar.db'),
  SESSION_SECRET: z
    .string({ error: 'SESSION_SECRET is required' })
    .min(32, 'SESSION_SECRET must be at least 32 characters'),
  ADMIN_PASSWORD_HASH: z
    .string({
      error: 'ADMIN_PASSWORD_HASH is required (run: pnpm --filter @team-radar/api hash-password)',
    })
    .startsWith(
      PASSWORD_HASH_PREFIX,
      'ADMIN_PASSWORD_HASH must be generated by the hash-password script',
    ),
  SESSION_TTL_HOURS: z.coerce
    .number()
    .int()
    .min(1)
    .max(24 * 90)
    .default(24 * 14),
  WEB_DIST_PATH: z.string().optional(),
  COOKIE_SECURE: booleanString.optional(),
  TRUST_PROXY: booleanString.default(false),
});

/** Typed, validated runtime configuration. Fails fast at startup on bad input. */
export class AppConfig {
  readonly env: 'development' | 'production' | 'test';
  readonly host: string;
  readonly port: number;
  readonly databasePath: string;
  readonly sessionSecret: string;
  readonly adminPasswordHash: string;
  readonly sessionTtlMs: number;
  readonly webDistPath: string | undefined;
  readonly cookieSecure: boolean;
  readonly trustProxy: boolean;

  private constructor(env: z.output<typeof envSchema>) {
    this.env = env.NODE_ENV;
    this.host = env.HOST;
    this.port = env.PORT;
    this.databasePath = env.DATABASE_PATH;
    this.sessionSecret = env.SESSION_SECRET;
    this.adminPasswordHash = env.ADMIN_PASSWORD_HASH;
    this.sessionTtlMs = env.SESSION_TTL_HOURS * 3_600_000;
    // Express needs an absolute path to serve the app's index.html for inner routes.
    this.webDistPath = env.WEB_DIST_PATH ? resolve(env.WEB_DIST_PATH) : undefined;
    this.cookieSecure = env.COOKIE_SECURE ?? env.NODE_ENV === 'production';
    this.trustProxy = env.TRUST_PROXY;
  }

  static fromEnv(source: NodeJS.ProcessEnv = process.env): AppConfig {
    const result = envSchema.safeParse(source);
    if (!result.success) {
      const details = result.error.issues
        .map((issue) => `  - ${issue.path.join('.')}: ${issue.message}`)
        .join('\n');
      throw new Error(`Invalid environment configuration:\n${details}`);
    }
    return new AppConfig(result.data);
  }
}
